Repository s-bhalode/Hacktoberfest-2023, pull requests merged in 2023-10, with the labels that each got.

#3 Added name
  participants/contributorsList.js
Labels: hactoberfest-accepted

#8 Added my Information
  contributors/participants/hardik.md
Labels: hactoberfest-accepted

#7 Update README.md
  README.md
  Slack CLONE/150ivrl50o3kryjq2a42.png
  Slack CLONE/A connected team discussing work in multiple channels in the Slack app.webm
  Slack CLONE/A user starting a huddle and recording a video clip with the Slack app.webm
  Slack CLONE/SEEK LOGO.png
  Slack CLONE/SLACK LOGO WHITE.png
  Slack CLONE/Screenshot 2023-09-24 110315.png
  Slack CLONE/Using the Workday integration to quickly file an expense report in the Slack app.webm
  Slack CLONE/XERO.png
  Slack CLONE/code.css
  Slack CLONE/code.html
  Slack CLONE/code.js
  Slack CLONE/deliveroo.png
  Slack CLONE/download-removebg-preview.png
  Slack CLONE/download.png
  Slack CLONE/google-logo (1).webp
  Slack CLONE/ia4-hero-product-ui.IN.webm
  Slack CLONE/image (2).png
  Slack CLONE/logo-ibm.png
  Slack CLONE/magnifying-glass (1).png
  Slack CLONE/new-slack-logo-nicolas-ciotti-removebg-preview.png
  Slack CLONE/new-slack-logo-nicolas-ciotti.jpg
  Slack CLONE/promo-boost-productivity.jpg
  Slack CLONE/promo-card-dreamforce-2023.png
  Slack CLONE/promo-open-ai.jpg
  Slack CLONE/rea.png
  Slack CLONE/rmit.png
  Slack CLONE/wtny-resource-tile.jpg
Labels: documentation, hactoberfest-accepted

#10 Added my Information
  contributors/Krish.md
Labels: documentation, hactoberfest-accepted, first time contributor

#5 added by aryankelwa
  contributors/participants/aryankelwa.md
Labels: hactoberfest-accepted

#1 vaibhava17
  .gitignore
  .vscode/settings.json
  contributors/participants/vaibhav.md
Labels: hactoberfest-accepted

#42 Create sohamkottawar.Md
  contributors/participants/sohamkottawar.Md
Labels: hactoberfest-accepted, hacktoberfest

#41 added ankur.md
  FOOTER CSS _--/_ Footer Section Start _/FOOTER
  contributors/participants/ankur.md
Labels: hactoberfest-accepted, hacktoberfest

#43 Hacktoberfest-2023/contributors /participants/ Akshada
  contributors/participants/Akshada
Labels: hactoberfest-accepted, hacktoberfest

#36 Create hritik.md
  contributors/participants/hritik.md
Labels: hactoberfest-accepted, hacktoberfest

#31 Adds my info
  contributors/participants/dmitry.md
Labels: hactoberfest-accepted, hacktoberfest

#46 Added aliamanatali.md
  contributors/participants/aliamanatali.md
Labels: hactoberfest-accepted, hacktoberfest

#49 Create SpiderMath.md
  contributors/participants/SpiderMath.md
Labels: hactoberfest-accepted, hacktoberfest

#50 Add Introduction
  contributors/participants/haiderali.md
Labels: hactoberfest-accepted, hacktoberfest
